default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: frontend_challenge_development

test:
  <<: *default
  database: frontend_challenge_test
